import { Deck } from "../types";

export const SAMPLE_DATA = [
  {
    name: 'Tier1',
    decks: [
      { name: 'R-ACE', image: '/public/static/deckimages/r-ace.png' },
      { name: '炎王', image: '/public/static/deckimages/fireking.jpg' },
      { name: 'スネークアイ', image: '/public/static/deckimages/snake-eye.png' },
      { name: '炎王スネークアイ', image: '/public/static/deckimages/fireking-snake-eye.png' },
    ],
  },
  {
    name: 'Tier2',
    decks: [
      { name: 'スプライト', image: '/public/static/deckimages/spright.png' },
      { name: 'ティアラメンツ', image: '/public/static/deckimages/tearlaments.png' },
    ],
  },
  {
    name: 'Tier3',
    decks: [
    ],
  },
  {
    name: 'Tier4',
    decks: [
    ],
  },
]

export const INITIAL_AVAILABLE_DECKS: Deck[] = [
  { name: 'ホルス', image: '/public/static/deckimages/spright.png' },
  { name: '60GS', image: '/public/static/deckimages/spright.png' },
  { name: 'PUNK', image: '/public/static/deckimages/spright.png' },
  { name: 'セフィラ', image: '/public/static/deckimages/spright.png' },
  { name: '覇王魔術師', image: '/public/static/deckimages/spright.png' },
  { name: '魔術師', image: '/public/static/deckimages/spright.png' },
  { name: 'メタビート', image: '/public/static/deckimages/spright.png' },
  { name: 'エンディミオン', image: '/public/static/deckimages/spright.png' },
  { name: 'エクソシスター', image: '/public/static/deckimages/spright.png' },
  { name: 'キマイラ', image: '/public/static/deckimages/spright.png' },
  { name: '斬機', image: '/public/static/deckimages/spright.png' },
  { name: '転生炎獣', image: '/public/static/deckimages/spright.png' },
  { name: '超重武者', image: '/public/static/deckimages/spright.png' },
  { name: 'ラビュリンス', image: '/public/static/deckimages/spright.png' },
  { name: 'イビルツイン', image: '/public/static/deckimages/spright.png' },
  { name: 'ピュアリィ', image: '/public/static/deckimages/spright.png' },
  { name: 'ゴスピュ', image: '/public/static/deckimages/spright.png' },
  { name: '十二獣', image: '/public/static/deckimages/spright.png' },
  { name: 'ふわんだりぃず', image: '/public/static/deckimages/spright.png' },
  { name: 'クシャトリラ', image: '/public/static/deckimages/spright.png' },
  { name: '御巫', image: '/public/static/deckimages/spright.png' },
  { name: '破械', image: '/public/static/deckimages/spright.png' },
  { name: 'マナドゥム', image: '/public/static/deckimages/spright.png' },
  { name: 'ノイド', image: '/public/static/deckimages/spright.png' },
  { name: 'オルターガイスト', image: '/public/static/deckimages/spright.png' },
  { name: 'VS', image: '/public/static/deckimages/spright.png' },
  { name: '幻影勇者', image: '/public/static/deckimages/spright.png' },
  { name: '＠イグニスター', image: '/public/static/deckimages/spright.png' },
  { name: '天威勇者', image: '/public/static/deckimages/spright.png' },
  { name: 'ヴァリアンツ', image: '/public/static/deckimages/spright.png' },
  { name: 'ドラゴンリンク', image: '/public/static/deckimages/spright.png' },
  { name: '神碑', image: '/public/static/deckimages/spright.png' },
  { name: 'ナチュル神碑', image: '/public/static/deckimages/spright.png' },
  { name: 'ナチュル', image: '/public/static/deckimages/spright.png' },
  { name: 'レッド・デーモン', image: '/public/static/deckimages/spright.png' },
  { name: '閃刀姫', image: '/public/static/deckimages/spright.png' },
  { name: '六花', image: '/public/static/deckimages/spright.png' },
  { name: '植物', image: '/public/static/deckimages/spright.png' },
  { name: 'プランキッズ', image: '/public/static/deckimages/spright.png' },
  { name: 'メメント', image: '/public/static/deckimages/spright.png' },
  { name: '烙印', image: '/public/static/deckimages/spright.png' },
  { name: '呪眼', image: '/public/static/deckimages/spright.png' },
  { name: '相剣', image: '/public/static/deckimages/spright.png' },
  { name: 'ドライトロン', image: '/public/static/deckimages/spright.png' },
  { name: 'HERO', image: '/public/static/deckimages/spright.png' },
  { name: '蠱惑魔', image: '/public/static/deckimages/spright.png' },
  { name: 'ヴァルモニカ', image: '/public/static/deckimages/spright.png' },
  { name: '恐竜', image: '/public/static/deckimages/spright.png' },
  { name: 'ダイノルフィア', image: '/public/static/deckimages/spright.png' },
  { name: 'ネムレリア', image: '/public/static/deckimages/spright.png' },
  { name: 'オルフェゴール', image: '/public/static/deckimages/spright.png' },
  { name: '海', image: '/public/static/deckimages/spright.png' },
  { name: '焔聖騎士', image: '/public/static/deckimages/spright.png' },
  { name: '未界域', image: '/public/static/deckimages/spright.png' },
  { name: '代行天使', image: '/public/static/deckimages/spright.png' },
  { name: '神碑スプライト', image: '/public/static/deckimages/spright.png' },
  { name: 'ヌメロン', image: '/public/static/deckimages/spright.png' },
  { name: 'スケアクロー', image: '/public/static/deckimages/spright.png' },
  { name: 'ビーステッドスプライト', image: '/public/static/deckimages/spright.png' },
  { name: 'ラクシャビス', image: '/public/static/deckimages/spright.png' },
  { name: 'ビーステッド神碑', image: '/public/static/deckimages/spright.png' },
  { name: 'BF', image: '/public/static/deckimages/spright.png' },
  { name: 'ヴォルカニック', image: '/public/static/deckimages/spright.png' },
  { name: '破壊剣', image: '/public/static/deckimages/spright.png' },
  { name: '竜剣士', image: '/public/static/deckimages/spright.png' },
  { name: 'リチュアスプライト', image: '/public/static/deckimages/spright.png' },
  { name: 'SPYRAL', image: '/public/static/deckimages/spright.png' },
  { name: '暗黒界', image: '/public/static/deckimages/spright.png' },
  { name: '召喚獣', image: '/public/static/deckimages/spright.png' },
  { name: 'サンダードラゴン', image: '/public/static/deckimages/spright.png' },
  { name: '捕食植物', image: '/public/static/deckimages/spright.png' },
  { name: 'シャドール', image: '/public/static/deckimages/spright.png' },
  { name: '海造賊', image: '/public/static/deckimages/spright.png' },
  { name: '王', image: '/public/static/deckimages/spright.png' },
  { name: 'サンアバロン', image: '/public/static/deckimages/spright.png' },
];
