import React from 'react';
import TierList from './components/TierList';

const App: React.FC = () => {
  return (
    <div className="container w-full max-w-[880px] mx-auto">
      <h1 className="text-4xl font-bold pt-4 md:pt-8 export-md:pt-8 mb-8 text-center" style={{
        fontFamily: 'Digital Numbers'
      }}>TIER MAKER</h1>
      <TierList />

      <footer className='flex px-4 justify-between items-center py-4 opacity-0' style={{
        width: '816px',
        maxWidth: '100%'
      }}>
        <div className='w-20 h-1'></div>
        <div className='text-sm flex-1 text-center'>Generated by <a href="https://tier.ygotools.com" target='_blank' className='underline'>https://tier.ygotools.com</a> created by @potato4d</div>
        <img src="/public/static/EXW.png" width="80" alt="teamEXTRAWIN" />
      </footer>
    </div>
  );
};

export default App;
